In [3]:
import geopandas as gpd
import numpy as np
import pandas as pd
import folium

In [4]:
filepath = "C:/Users/kevin.turnbow/GIS/LAKES26.shp"
gdf = gpd.read_file(filepath)
#gdf.to_crs('epsg:4326')
gdf

  ASSESSMENT  ...                                           geometry
0     IL_RBA  ...  POLYGON Z ((-88.11556 39.03167 0, -88.11553 39...
1     IL_RBB  ...  MULTIPOLYGON Z (((-87.83474 38.72836 0, -87.83...
2     IL_RCD  ...  POLYGON Z ((-88.74963 38.73021 0, -88.74958 38...
3     IL_ROI  ...  POLYGON Z ((-88.98746 38.56422 0, -88.9877 38....
4     IL_ROK  ...  POLYGON Z ((-89.06759 38.53224 0, -89.06763 38...

[5 rows x 9 columns]

In [5]:
# Your provided dictionaries
lakesizeles10 = {
    "size" : "lakesizeles10",
    "ttlptts" : "20",
    "surf_secc" : "13",
    "surf_2secc" : "7"
}
lakesize10 = {
    "size" : "lakesize10",
    "ttlptts" : "30",
    "surf_secc" : "20",
    "surf_2secc" : "10"
}
lakesize50 = {
    "size" : "lakesize50",
    "ttlptts" : "40",
    "surf_secc" : "27",
    "surf_2secc" : "13"
}
lakesize100 = {
    "size" : "lakesize100",
    "ttlptts" : "50",
    "surf_secc" : "34",
    "surf_2secc" : "16"
}
lakesize200 = {
    "size" : "lakesize200",
    "ttlptts" : "60",
    "surf_secc" : "40",
    "surf_2secc" : "20"
}
lakesize300 = {
    "size" : "lakesize300",
    "ttlptts" : "70",
    "surf_secc" : "48",
    "surf_2secc" : "22"
}
lakesize400 = {
    "size" : "lakesize400",
    "ttlptts" : "80",
    "surf_secc" : "53",
    "surf_2secc" : "27"
}
lakesize500 = {
    "size" : "lakesize500",
    "ttlptts" : "90",
    "surf_secc" : "60",
    "surf_2secc" : "30"
}
lakesize800 = {
    "size" : "lakesize800",
    "ttlptts" : "100",
    "surf_secc" : "67",
    "surf_2secc" : "33"
}

# Consolidate into a list
lake_size_data_list = [
    lakesizeles10,
    lakesize10,
    lakesize50,
    lakesize100,
    lakesize200,
    lakesize300,
    lakesize400,
    lakesize500,
    lakesize800
]

print("Consolidated List of Dictionaries:")
for item in lake_size_data_list:
    print(item)

Consolidated List of Dictionaries:
{'size': 'lakesizeles10', 'ttlptts': '20', 'surf_secc': '13', 'surf_2secc': '7'}
{'size': 'lakesize10', 'ttlptts': '30', 'surf_secc': '20', 'surf_2secc': '10'}
{'size': 'lakesize50', 'ttlptts': '40', 'surf_secc': '27', 'surf_2secc': '13'}
{'size': 'lakesize100', 'ttlptts': '50', 'surf_secc': '34', 'surf_2secc': '16'}
{'size': 'lakesize200', 'ttlptts': '60', 'surf_secc': '40', 'surf_2secc': '20'}
{'size': 'lakesize300', 'ttlptts': '70', 'surf_secc': '48', 'surf_2secc': '22'}
{'size': 'lakesize400', 'ttlptts': '80', 'surf_secc': '53', 'surf_2secc': '27'}
{'size': 'lakesize500', 'ttlptts': '90', 'surf_secc': '60', 'surf_2secc': '30'}
{'size': 'lakesize800', 'ttlptts': '100', 'surf_secc': '67', 'surf_2secc': '33'}

In [6]:
lake_size_lookup_df = pd.DataFrame(lake_size_data_list)

# Convert relevant columns to numeric types for easier use
# Note: 'size' column will remain string as it contains ranges/operators
for col in ['ttlptts', 'surf_secc', 'surf_2secc']:
    lake_size_lookup_df[col] = pd.to_numeric(lake_size_lookup_df[col])

lake_size_lookup_df

            size  ttlptts  surf_secc  surf_2secc
0  lakesizeles10       20         13           7
1     lakesize10       30         20          10
2     lakesize50       40         27          13
3    lakesize100       50         34          16
4    lakesize200       60         40          20
5    lakesize300       70         48          22
6    lakesize400       80         53          27
7    lakesize500       90         60          30
8    lakesize800      100         67          33

In [7]:
gdf['TESTACRES'] = gdf['WATER_SIZE'].astype(float)
gdf

  ASSESSMENT  ... TESTACRES
0     IL_RBA  ...     180.0
1     IL_RBB  ...      40.0
2     IL_RCD  ...     525.0
3     IL_ROI  ...     450.0
4     IL_ROK  ...     925.0

[5 rows x 10 columns]

In [8]:
import geopandas as gpd

# 1. Load your GeoDataFrame
gdf = gpd.read_file(filepath)

# 2. Reproject to a local projected CRS (Example: UTM Zone 15N - EPSG:32615)
# Replace 'EPSG:32615' with the appropriate UTM zone or local projected CRS for your geographic area
gdf_projected = gdf.to_crs(epsg=32615)

# 3. Calculate the perimeter in meters (standard for most projected CRS)
perimeter_meters = gdf_projected.geometry.length

# 4. Convert meters to yards (1 meter = 1.09361 yards)
gdf['perimtr_yd'] = perimeter_meters * 1.09361

# View the result
print(gdf[['perimtr_yd']])

     perimtr_yd
0  16387.257328
1   4589.993050
2  37150.413916
3  22775.943602
4  22136.370694

In [9]:
bins = [0, 10, 50, 100, 200, 300, 400, 500, 800, np.inf] # np.inf for the upper bound of the last category
labels = lake_size_lookup_df['size'].tolist() # Use the 'size' strings as labels
gdf['Lake_Size_Category'] = pd.cut(
    gdf['WATER_SIZE'],
    bins=bins,
    labels=labels,
    right=False, # Important for correct binning based on your ranges
    include_lowest=True # Include 0 in the first bin
)
gdf = gdf.merge(
    lake_size_lookup_df,
    left_on='Lake_Size_Category',
    right_on='size',
    how='left' # Use left join to keep all lakes from your GeoDataFrame
)
gdf['dist'] = (gdf['perimtr_yd']* 0.9144) / gdf['ttlptts']
#gdf.drop('size', axis=1, inplace=True)
gdf

  ASSESSMENT         ASSESSME_1  EPA_IR_CAT  ... surf_secc  surf_2secc        dist
0     IL_RBA           SAM PARR         5.0  ...        34          16  299.690162
1     IL_RBB  RED HILLS ST PARK         5.0  ...        20          10  139.902988
2     IL_RCD  STEPHEN A. FORBES         5.0  ...        60          30  377.448205
3     IL_ROI          CENTRALIA         5.0  ...        53          27  260.329035
4     IL_ROK            RACCOON         5.0  ...        67          33  202.414974

[5 rows x 16 columns]

In [20]:

m = gdf.explore()
m

In [11]:
temp_shp = gdf.to_file('C:/Users/kevin.turnbow/GIS/LAKES25_processed.shp')

<positron-console-cell-11>:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Lake_Size_Category' to 'Lake_Size_'
  ogr_write(

In [21]:
all_points = []

for i in range(len(gdf)):
    # Reproject this lake's geometry to UTM (meters) so distances match `dist` (meters)
    geom_utm = gpd.GeoSeries([gdf.geometry.iloc[i]], crs=gdf.crs).to_crs(epsg=32615).iloc[0]
    boundary_line = geom_utm.boundary
    dis = gdf['dist'].iloc[i]

    if pd.isna(dis) or dis <= 0:
        print(f"Skipping index {i} ({gdf['ASSESSMENT'].iloc[i]}): invalid dist ({dis})")
        continue

    fixed_interval = dis
    distances = np.arange(0, boundary_line.length, fixed_interval)
    points_utm = [boundary_line.interpolate(distance) for distance in distances]

    lake_points_gdf = gpd.GeoDataFrame(geometry=points_utm, crs='EPSG:32615')
    lake_points_gdf = lake_points_gdf.to_crs(gdf.crs)  # back to lat/lon
    lake_points_gdf = lake_points_gdf.reset_index(level=0)
    lake_points_gdf['index'] = lake_points_gdf['index'] + 1
    lake_points_gdf['indexa'] = lake_points_gdf['index'].apply(lambda x: 'S' if x % 3 else 'D')

    name = gdf['ASSESSMENT'].iloc[i]
    lake_points_gdf['code'] = name + lake_points_gdf['index'].astype('string') + '_Macroph-' + lake_points_gdf['indexa']
    lake_points_gdf = lake_points_gdf.drop(['index', 'indexa'], axis=1)

    # Per-lake shapefile (same as before, now for every lake instead of just index 0)
    lake_points_gdf.to_file('C:/Users/kevin.turnbow/GIS/' + name + '_processed.shp')

    all_points.append(lake_points_gdf)

# Combine every lake's points into one GeoDataFrame for the GPX export below
sampled_points_gdf = pd.concat(all_points, ignore_index=True)
sampled_points_gdf = gpd.GeoDataFrame(sampled_points_gdf, geometry='geometry', crs=gdf.crs)

print(f"Generated {len(sampled_points_gdf)} points across {len(all_points)} lakes")
sampled_points_gdf.explore(color='blue')

sampled_points_gdf.explore(m=m, color="red")

Generated 355 points across 5 lakes

In [13]:
sampled_points_gdf = sampled_points_gdf.set_geometry(sampled_points_gdf.geometry.force_2d())
sampled_points_gdf

                       geometry                 code
0    POINT (-88.11556 39.03167)    IL_RBA1_Macroph-S
1     POINT (-88.11698 39.0298)    IL_RBA2_Macroph-S
2    POINT (-88.11706 39.02745)    IL_RBA3_Macroph-D
3    POINT (-88.11701 39.02541)    IL_RBA4_Macroph-S
4    POINT (-88.11534 39.02485)    IL_RBA5_Macroph-S
..                          ...                  ...
350   POINT (-89.06746 38.5322)   IL_ROK97_Macroph-S
351  POINT (-89.06724 38.53378)   IL_ROK98_Macroph-S
352  POINT (-89.06918 38.53323)   IL_ROK99_Macroph-D
353  POINT (-89.06902 38.53374)  IL_ROK100_Macroph-S
354   POINT (-89.06919 38.5337)  IL_ROK101_Macroph-S

[355 rows x 2 columns]

In [14]:
# GPX only supports a fixed waypoint schema (name, desc, cmt, ele, time, etc.) -
# it will reject a custom field like 'code' unless renamed to a supported field.
gpx_export_gdf = sampled_points_gdf.rename(columns={'code': 'name'})[['name', 'geometry']]

gpx_export_gdf.to_file('C:/Users/kevin.turnbow/GIS/LAKES25_processed.gpx', driver="GPX")

C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA1_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA2_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA3_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA4_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA5_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA6_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA7_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA8_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA9_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA10_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA11_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA12_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA13_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA14_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA15_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA16_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA17_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA18_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA19_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA20_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA21_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA22_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA23_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA24_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA25_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA26_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA27_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA28_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA29_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA30_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA31_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA32_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA33_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA34_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA35_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA36_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA37_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA38_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA39_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA40_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA41_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA42_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA43_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA44_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA45_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA46_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA47_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA48_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA49_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA50_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBA51_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB1_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB2_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB3_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB4_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB5_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB6_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB7_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB8_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB9_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB10_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB11_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB12_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB13_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB14_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB15_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB16_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB17_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB18_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB19_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB20_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB21_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB22_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB23_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB24_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB25_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB26_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB27_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB28_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB29_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB30_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RBB31_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD1_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD2_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD3_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD4_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD5_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD6_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD7_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD8_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD9_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD10_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD11_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD12_Macroph-D' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD13_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(
C:\Users\kevin.turnbow\AppData\Roaming\Python\Python313\site-packages\pyogrio\raw.py:733: RuntimeWarning: Value 'IL_RCD14_Macroph-S' of field LAKES25_processed.ele parsed incompletely to real 0.
  ogr_write(